# Site settings
title: Cinjon
email: cinjon@alum.mit.edu
description: > # this means to ignore newlines until "baseurl:"
  Cinjon's on the internet
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cinjon.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  cinjon

# Build settings
markdown: kramdown
kramdown:
  input: GFM

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-46142066-1          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

plugins:
  - jekyll-analytics
